import Head from 'next/head'
import { Header, Hero, Row } from '../companets' // hamma companentlani index ga yozin indexni chaqirib olsak osonroq
import { useEffect } from 'react';
import { API_REQUEST } from '../services/api.service';
import { getServers } from 'dns';
import { GetServerSideProps } from 'next';
import { IMovie } from '../interfaces/app.interface';

export default function Home({trending, topReated}: HomeProps): JSX.Element {
  // useEffect(() => {
  //   fetch(API_REQUEST.trending)
  //   .then(res => res.json())
  //   .then(data => console.log(data))
  // }, [])

  return (
    <div className='relative h-[200vh]'>
      <Head>
        <title>Home - Jahon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header/>
      <main className='relative pl-4 pb-24 lg:space-y-24 lg:pl-16'>
       {/* Hero */}
       <Hero trending={trending}/>
       <Row title='Top Rated' movies={topReated} />
       <section>
        {/* Row */}
        {/* BigRow */}
        {/* Row */}
        {/* BigRow */}
       </section>
      </main>
    </div>
  )
}

// SSR yozish
export const getServerSideProps: GetServerSideProps<HomeProps> = async () => {
  const trending = await fetch(API_REQUEST.trending).then(res => res.json());
  const topReated = await fetch(API_REQUEST.top_reted).then(res => res.json());

  // kirgandan poshqa page ga o'tib ketadi
  // if(trending.results.length) {
  //   return{
  //     notFound: true, // error 404 ga yuboradi
  //   }
  // }

  return{
    props: {
      trending: trending.results,
      topReated: topReated.results,
    }
  }
}
interface HomeProps {
  trending: IMovie[];
  topReated: IMovie[]
}